// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2f4IflBQR86LXUCUJq5vxyjekFbgotuQ',
    appId: '1:706653603540:web:1af6d6f51f0d25c4211d41',
    messagingSenderId: '706653603540',
    projectId: 'lingo-breeze-7c616',
    authDomain: 'lingo-breeze-7c616.firebaseapp.com',
    storageBucket: 'lingo-breeze-7c616.firebasestorage.app',
    measurementId: 'G-DGQN2VNJEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYZtEg8wZfbN60s7jXr7b4U7ODLEzhl0I',
    appId: '1:706653603540:android:ca30c654a15c4f90211d41',
    messagingSenderId: '706653603540',
    projectId: 'lingo-breeze-7c616',
    storageBucket: 'lingo-breeze-7c616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYYvVf4blfB0elW-cKkGjAHXcLASJ_u2I',
    appId: '1:706653603540:ios:517bd7bd0bde1b7f211d41',
    messagingSenderId: '706653603540',
    projectId: 'lingo-breeze-7c616',
    storageBucket: 'lingo-breeze-7c616.firebasestorage.app',
    iosBundleId: 'com.vhx.lingobreeze',
  );
}
